# Generated by Django 4.2.16 on 2024-11-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exchangerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_unit', models.CharField(max_length=10)),
                ('cur_nm', models.CharField(max_length=100)),
                ('ttb', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('tts', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('deal_bas_r', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('bkpr', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('yy_efee_r', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ten_dd_efee_r', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('kftc_deal_bas_r', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('kftc_bkpr', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
    ]
